config/routes.rb
LemonDocs::Application.routes.draw do
  get "home/index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "/users/auth/:provider" => "users/omniauth_callbacks#passthru"

  resources :organizations do
    resources :projects
  end

  get "projects" => "home#projects"  
  match 'projects/:id' => 'home#project'

  root :to => "home#index"

end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :user_id, :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  attr_accessible :provider, :uid, :user_id, :token
  
end

app/models/lemonhub.rb
class LemonHub   < ActiveRecord::Base
  
  def self.github(current_user)
    if (current_user and !@current_github)
      github =  Github.new oauth_token: current_user.authorizations.find_by_provider(:github).token 
      @current_github = github
    end
    @current_github
  end

  def self.organizations
    @current_github.orgs.list
  end

  def self.projects (organization_id)
    team_list = @current_github.orgs.teams.list organization_id
    project_list = @current_github.orgs.teams.list_repos team_list.first[:id]
    project_list
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  attr_accessible :provider, :uid

  has_many :authorizations

  def self.find_for_github_oauth(auth, signed_in_resource=nil)
    #user = User.where(:provider => auth.provider, :uid => auth.uid).first
    authorization = Authorization.find_by_provider_and_uid(auth.provider, auth.uid)
    if (authorization) 
      user = authorization.user 
    end

    unless user
      user = User.create(name:auth.extra.raw_info.name,
                           email:auth.info.email,
                           password:Devise.friendly_token[0,20]
                           )
      user.authorizations.build(:provider => auth.provider, :uid => auth.uid, :token =>(auth['credentials']['token'] rescue nil))
    end
    puts user 
    user
  end

  def apply_omniauth(omniauth)
    case omniauth['provider']
    when 'github'
      self.apply_github(omniauth)
    end
    authorizations.build(:provider => omniauth['provider'], :uid => omniauth['uid'], :token =>(omniauth['credentials']['token'] rescue nil))
  end

  def github
    #@github_user ||= FbGraph::User.me(self.authorizations.find_by_provider('facebook').token)
  end


  protected

  def apply_github(omniauth)
    if (extra = omniauth['extra']['user_hash'] rescue false)
      self.email = (extra['email'] rescue '')
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authenticate_user!
  protect_from_forgery
 
  
end

app/controllers/home_controller.rb
require 'lemonhub'
class HomeController < ApplicationController
  
  def index
    LemonHub.github current_user
    @organizations = LemonHub.organizations
  end

end

app/controllers/organizations_controller.rb
require 'lemonhub'

class OrganizationsController < ApplicationController
  
  def show
    if (current_user)
      github = LemonHub.github current_user
      @organization_id = params["id"]
      @project_list = LemonHub.projects @organization_id
      @users = github.activity.events.user_org "abrahambarrera", @organization_id

    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def show
    if (current_user)
      github = LemonHub.github current_user
      @organization_id = params["organization_id"]
      @project_id = params["id"]
      @project_list = LemonHub.projects @organization_id
    end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def github
    
    @user = User.find_for_github_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Github") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  # def method_missing(provider)
  #   if !User.omniauth_providers.index(provider).nil?
  #     #omniauth = request.env["omniauth.auth"]
  #     omniauth = env["omniauth.auth"]
  #     puts "**************************"
  #     puts "**************************"
  #     puts omniauth 
  #     puts "**************************"
  #     puts "**************************"
  #     if current_user #or User.find_by_email(auth.recursive_find_by_key("email"))
  #       puts "******** UPDATE USER "
  #       current_user.authorizations.find_or_create_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
  #        flash[:notice] = "Authentication successful"
  #        redirect_to edit_user_registration_path
  #     else

  #     authentication = Authorization.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'])

  #       if authentication
  #         flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => omniauth['provider']
  #         sign_in_and_redirect(:user, authentication.user)
  #         #sign_in_and_redirect(authentication.user, :event => :authentication)
  #       else

  #         #create a new user
  #         unless omniauth.recursive_find_by_key("email").blank?
  #           user = User.find_or_initialize_by_email(:email => omniauth.recursive_find_by_key("email"))
  #         else
  #           user = User.new
  #         end

  #         user.apply_omniauth(omniauth)
  #         #user.confirm! #unless user.email.blank?

  #         if user.save
  #           flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => omniauth['provider']
  #           sign_in_and_redirect(:user, user)
  #         else
  #           session[:omniauth] = omniauth.except('extra')
  #           redirect_to new_user_registration_url
  #         end
  #       end
  #     end
  #   end
  # end

end

class Hash
  def recursive_find_by_key(key)
    # Create a stack of hashes to search through for the needle which
    # is initially this hash
    stack = [ self ]

    # So long as there are more haystacks to search...
    while (to_search = stack.pop)
      # ...keep searching for this particular key...
      to_search.each do |k, v|
        # ...and return the corresponding value if it is found.
        return v if (k == key)

        # If this value can be recursively searched...
        if (v.respond_to?(:recursive_find_by_key))
          # ...push that on to the list of places to search.
          stack << v
        end
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper

  def event_types
    @event_types = {
      "CommitCommentEvent" => {:color => "success", :name => "commit"},
      "CreateEvent" => {:color => "info", :name => "Create", :field => "description"},
      "DeleteEvent" => {:color => "important", :name => "Delete", :field => "ref"},
      "DownloadEvent" => {:color => "default", :name => "Download"},
      "FollowEvent" => {:color => "default", :name => "Follow"},
      "ForkEvent" => {:color => "default", :name => "Fork"},
      "ForkApplyEvent" => {:color => "default", :name => "Forked"},
      "GistEvent" => {:color => "default", :name => "Gist"},
      "GollumEvent" => {:color => "default", :name => "Gollum"},
      "IssueCommentEvent" => {:color => "inverse", :name => "Comment"},
      "IssuesEvent" => {:color => "inverse", :name => "Issue"},
      "MemberEvent" => {:color => "info", :name => "Member"},
      "PublicEvent" => {:color => "default", :name => "Public"},
      "PullRequestEvent" => {:color => "warning", :name => "Pull Request", :field => "body"},
      "PullRequestReviewCommentEvent"=> {:color => "inverse", :name => "Comment"},
      "PushEvent" => {:color => "success", :name => "Push"},
      "TeamAddEvent"=> {:color => "default", :name => "Team Add"},
      "WatchEvent"=> {:color => "default", :name => "Watch"}
    }
    @event_types
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/index.html.haml
#main
  .span12
    %h5 Select an Organization to Continue
    %p
      = select("member", "organization", @organizations.collect {|p| [ p.login, p.id ] })
      %br  
      = link_to "Go!", organization_path("LemontechSA"), :class=>"btn btn-success", :id=>"select_organization"
 
   

app/views/home/project.html.haml
#main
  .span3
    .well.sidebar-nav
      %ul.nav.nav-list
        %li.nav-header Projects
        - @project_list.each do |p|
          %li= link_to "#{p.name}", "/projects/#{p.id}"
  .span9
    .row-fluid
      .span6
        %h4 Project
        %p
          %table.table.table-condensed.table-bordered.table-striped.table-hover
            %th
              Feature Name
            %tr
              %td Holaa

      .span6
        %h4 Hotfixes
        %p
    .row-fluid
      .span6
        %h4 Releases
        %p
      .span6
        %h4 Pull Requests
        %p
    %br
   

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
      %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}
        %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
          %title= content_for?(:title) ? yield(:title) : "LemonHub"
          = csrf_meta_tags
          / Le HTML5 shim, for IE6-8 support of HTML elements
          /[if lt IE 9]
            <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
          = stylesheet_link_tag "application", :media => "all"
          / For third-generation iPad with high-resolution Retina display:
          / Size should be 144 x 144 pixels
          = favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
          / For iPhone with high-resolution Retina display:
          / Size should be 114 x 114 pixels
          = favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
          / For first- and second-generation iPad:
          / Size should be 72 x 72 pixels
          = favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
          / For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
          / Size should be 57 x 57 pixels
          = favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
          / For all other devices
          / Size should be 32 x 32 pixels
          = favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon'
  %body
    #wrap
      .navbar.navbar-fluid-top
        .navbar-inner
          .container-fluid
            %a.brand{:href => "#"} 
              %i.icon-signal
              LemonHub
      .container-fluid
        %ul.nav.nav-pills.pull-right
          %li.active
            - if current_user
              = link_to destroy_user_session_path, :method => :delete do
                %i.icon-user
                = "Logout (#{current_user.name}) "
        .row-fluid
          .span12
            = bootstrap_flash
            %div{"data-pjax-container" => ""}
              = yield
    #footer
      .container
        %p.muted.credit
          © Lemontech 2012
    = javascript_include_tag "application"

app/views/organizations/show.html.haml
#main
  .span3
    .well.sidebar-nav
      %ul.nav.nav-list
        %li.nav-header Projects
        - @project_list.each do |p|
          %li
            = link_to organization_project_path(@organization_id,"#{p.id}") do
              %i.icon-lock
              = "#{p.name}"
  .span9
    .row-fluid
      .span12
        %h4 Last Events
        %p
          %table.table.table-condensed.table-bordered.table-striped.table-hover
            %th
              User
            %th
              Event
            - types = event_types
            - @users.each do |u|
              %tr
                %td 
                  %img.img-circle{:src=>"#{u.actor.avatar_url}"}
                %td 
                  %span{:class => "label label-#{types[u.type][:color]}"}
                    = types[u.type][:name]
                  = link_to organization_project_path(@organization_id,"#{u.repo.id}") do
                    %i.icon-lock
                    = "#{u.repo.name}"
                  -if u.payload.commits
                    %br
                    = u.payload.commits.collect{|c| c.message}.join('<br/>').html_safe
                  - elsif u.payload.comment
                    = u.payload.comment.body
                  - elsif u.payload.pull_request
                    = u.payload.pull_request.body
                  - elsif u.payload.issue
                    = u.payload.issue.body
                  - else
                    - if u.payload[types[u.type][:field]]
                      = u.payload[types[u.type][:field]]

                

app/views/projects/show.html.haml
#main
  .span3
    .well.sidebar-nav
      %ul.nav.nav-list
        %li.nav-header Projects
        - @project_list.each do |p|
          %li
            = link_to organization_project_path(@organization_id,"#{p.id}") do
              %i.icon-lock
              = "#{p.name}"
  .span9
    .row-fluid
      .span6
        %h4 Project
        %p
          %table.table.table-condensed.table-bordered.table-striped.table-hover
            %th
              Feature Name
            %tr
              %td Holaa

      .span6
        %h4 Hotfixes
        %p
    .row-fluid
      .span6
        %h4 Releases
        %p
      .span6
        %h4 Pull Requests
        %p
    %br